@baseUrl=http://localhost:8082/v1/2024

#user register

POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "verify_key": "tipsgolang+00002@gmail.com",
  "verify_purpose": "TEST_USER",
  "verify_type": 1
}