// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type PreGoAccUserTwoFactor9999TwoFactorAuthType string

const (
	PreGoAccUserTwoFactor9999TwoFactorAuthTypeEMAIL PreGoAccUserTwoFactor9999TwoFactorAuthType = "EMAIL"
	PreGoAccUserTwoFactor9999TwoFactorAuthTypeSMS   PreGoAccUserTwoFactor9999TwoFactorAuthType = "SMS"
	PreGoAccUserTwoFactor9999TwoFactorAuthTypeAPP   PreGoAccUserTwoFactor9999TwoFactorAuthType = "APP"
)

func (e *PreGoAccUserTwoFactor9999TwoFactorAuthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PreGoAccUserTwoFactor9999TwoFactorAuthType(s)
	case string:
		*e = PreGoAccUserTwoFactor9999TwoFactorAuthType(s)
	default:
		return fmt.Errorf("unsupported scan type for PreGoAccUserTwoFactor9999TwoFactorAuthType: %T", src)
	}
	return nil
}

type NullPreGoAccUserTwoFactor9999TwoFactorAuthType struct {
	PreGoAccUserTwoFactor9999TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
	Valid                                      bool // Valid is true if PreGoAccUserTwoFactor9999TwoFactorAuthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPreGoAccUserTwoFactor9999TwoFactorAuthType) Scan(value interface{}) error {
	if value == nil {
		ns.PreGoAccUserTwoFactor9999TwoFactorAuthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PreGoAccUserTwoFactor9999TwoFactorAuthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPreGoAccUserTwoFactor9999TwoFactorAuthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PreGoAccUserTwoFactor9999TwoFactorAuthType), nil
}

// Account
type GoCrmUser struct {
	// Account ID
	UsrID uint32
	// Email
	UsrEmail string
	// Phone Number
	UsrPhone string
	// Username
	UsrUsername string
	// Password
	UsrPassword string
	// Created Time
	UsrCreatedAt int32
	// Updated Time
	UsrUpdatedAt int32
	// Created IP
	UsrCreateIpAt string
	// Last Login Time
	UsrLastLoginAt int32
	// Last Login IP
	UsrLastLoginIpAt string
	// Login Times
	UsrLoginTimes int32
	// Status
	UsrStatus bool
}

type PreGoAccUserBase9999 struct {
	// User ID
	UserID int32
	// User account
	UserAccount string
	// User password
	UserPassword string
	// Salt for hashing
	UserSalt string
	// Last login timestamp
	UserLoginTime sql.NullTime
	// Last logout timestamp
	UserLogoutTime sql.NullTime
	// IP address of last login
	UserLoginIp sql.NullString
	// Creation timestamp
	UserCreatedAt sql.NullTime
	// Update timestamp
	UserUpdatedAt sql.NullTime
	// authentication two factor enabled for the user
	IsTwoFactorEnabled sql.NullInt32
}

type PreGoAccUserInfo9999 struct {
	// User  ID
	UserID uint64
	// User  account
	UserAccount string
	// User  nickname
	UserNickname sql.NullString
	// User  avatar
	UserAvatar sql.NullString
	// User  state: 0-Locked, 1-Activated, 2-Not Activated
	UserState uint8
	// Mobile phone number
	UserMobile sql.NullString
	// User  gender: 0-Secret, 1-Male, 2-Female
	UserGender sql.NullInt16
	// User  birthday
	UserBirthday sql.NullTime
	// User  email address
	UserEmail sql.NullString
	// Authentication status: 0-Not Authenticated, 1-Pending, 2-Authenticated, 3-Failed
	UserIsAuthentication uint8
	// Record creation time
	CreatedAt sql.NullTime
	// Record update time
	UpdatedAt sql.NullTime
}

// pre_go_acc_user_two_factor_9999
type PreGoAccUserTwoFactor9999 struct {
	// Khoa chinh tu dong tang
	TwoFactorID uint32
	// Khoa ngoai lien ket voi bang nguoi dung
	UserID uint32
	// Loai xac thuc 2fa
	TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
	// Ma bi mat xac thuc 2fa
	TwoFactorAuthSecret string
	// So dien thoai xac thuc 2fa
	TwoFactorPhone sql.NullString
	// Email xac thuc 2fa
	TwoFactorEmail sql.NullString
	// Trang thai kich hoat xac thuc 2fa
	TwoFactorIsActive bool
	// Thoi gian tao xac thuc 2fa
	TwoFactorCreatedAt sql.NullTime
	// Thoi gian cap nhat xac thuc 2fa
	TwoFactorUpdatedAt sql.NullTime
}

type PreGoAccUserVerify9999 struct {
	// Verification ID
	VerifyID int32
	// One-time password
	VerifyOtp string
	// Verification key - email address, phone number, ....
	VerifyKey string
	// Hash of the verification key
	VerifyKeyHash string
	// Verification type (e.g., 1 for email)
	VerifyType sql.NullInt32
	// Verification status: 1 for verified, 0 for not verified
	IsVerified sql.NullInt32
	// Deletion flag: 1 for deleted, 0 for not deleted
	IsDeleted sql.NullInt32
	// Record creation time
	VerifyCreatedAt sql.NullTime
	// Record update time
	VerifyUpdatedAt sql.NullTime
}
