version: '3.9'
networks:
  go-ecommerce-local-network:
    driver: bridge

services:

#  mysql:
#    image: mysql:8.0
#    container_name: mysql_container
#    environment:
#      MYSQL_ROOT_PASSWORD: root1234
#      MYSQL_DATABASE: shopdevgo
#      MYSQL_PASSWORD: root1234
#    ports:
#      - "33306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - ./init:/docker-entrypoint-initdb.d
  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6331:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - go-ecommerce-local-network
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_container
    ports:
      - "15540:5540"
    environment:
      - REDIS_HOSTS=redis:6379
    depends_on:
      - redis
    networks:
      - go-ecommerce-local-network

  kafka:
    image: 'bitnami/kafka:3.5'
    container_name: kafka_container
    environment:
      # cluster configuration
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9094

      # Listener configurations
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091,CONTROLLER://:9094,EXTERNAL://:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT

      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9091,EXTERNAL://localhost:9095
        
      # Performance and operational settings
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1

      # Heap and performance tuning
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms512M
        # Authentication
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Log retention
      - KAFKA_CFG_LOG_RETENTION_HOURS=168
      - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824






    volumes:
      - ./data/kafka_data:/bitnami/kafka
    networks:
      - go-ecommerce-local-network

    ports:
      - "19094:9094"
      - "19095:9095"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui_container
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka_container:9094
    ports:
      - "9090:8080"
    depends_on:
      - kafka
    networks:
      - go-ecommerce-local-network

volumes:
  redis_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local