server:
  port: 8082
  mode: "dev" # default: dev, options: dev, prod
mysql:
  host: 127.0.0.1
  port: 33306
  username: root
  password: root1234
  dbName: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
redis:
  host: 127.0.0.1
  port: 6331
  passsword:
  db: 0
  pool_size: 10
zookeeper:
  host: 127.0.0.1
  port: 2181
  #  TODO complete the configuration
kafak:
  host: 127.0.0.1
  port_internal: 9092
  port_external: 9094
  # brokers:
  #   -
  #  TODO complete the configuration
kafka_ui:
  host: 127.0.0.1
  port: 8083

smtp:
  host: smtp.gmail.com
  port: 587
  username:
  password:
send_grid:
  api_key: ""

rabbitmq:
  url_rb_d: ""


jwt:
  TOKEN_HOUR_LIFESPAN: 1
  JWT_EXPIRATION: 1h
  API_SECRET: "xxx.yyy.zzz"

monitoring:
  prometheus_port: 9090
  grafana_port: 3000
  grafana_admin_user: admin
  grafana_admin_password: admin
  node_exporter_port: 9100
  redis_exporter_port: 9121
  mysql_exporter_port: 9104
  kafka_exporter_port: 9308



