global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "go-ecommerce-kafka"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "host.docker.internal:9308" # kafka Exporter

  - job_name: "go-ecommerce-mysql"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "host.docker.internal:9104" # MySQL Exporter

  - job_name: "go-ecommerce-redis"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "host.docker.internal:9121" # Redis Exporter

  - job_name: "go-ecommerce-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "host.docker.internal:9090" # Prometheus itself

  - job_name: "go-ecommerce-node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "node-exporter:9100" # Node Exporter

  - job_name: 'go-ecommerce'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'host.docker.internal:8082'

